/* 
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MMSApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class MMSApiTests
    {
        private MMSApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MMSApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MMSApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MMSApi
            //Assert.IsInstanceOfType(typeof(MMSApi), instance, "instance is a MMSApi");
        }

        
        /// <summary>
        /// Test MmsPricePost
        /// </summary>
        [Test]
        public void MmsPricePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MmsMessageCollection mmsMessages = null;
            //var response = instance.MmsPricePost(mmsMessages);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test MmsSendPost
        /// </summary>
        [Test]
        public void MmsSendPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MmsMessageCollection mmsMessages = null;
            //var response = instance.MmsSendPost(mmsMessages);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
