/* 
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using IO.ClickSend.Client;
using IO.ClickSend.ClickSend.Api;
using IO.ClickSend.ClickSend.Model;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace IO.ClickSend.Test
{
    /// <summary>
    ///  Class for testing EmailToSmsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by ClickSend Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestClass]
    public class EmailToSmsApiTests
    {
        private EmailToSmsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            instance = new EmailToSmsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmailToSmsApi
        /// </summary>
        [TestMethod]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EmailToSmsApi
            //Assert.IsInstanceOfType(typeof(EmailToSmsApi), instance, "instance is a EmailToSmsApi");
        }

        /// <summary>
        /// Test SmsEmailSmsGet
        /// </summary>
        [TestMethod]
        public void SmsEmailSmsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? limit = null;
            //var response = instance.SmsEmailSmsGet(page, limit);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test SmsEmailSmsPost
        /// </summary>
        [TestMethod]
        public void SmsEmailSmsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EmailSMSAddress body = null;
            //var response = instance.SmsEmailSmsPost(body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test SmsEmailSmsStrippedStringDelete
        /// </summary>
        [TestMethod]
        public void SmsEmailSmsStrippedStringDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? ruleId = null;
            //var response = instance.SmsEmailSmsStrippedStringDelete(ruleId);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test SmsEmailSmsStrippedStringGet
        /// </summary>
        [TestMethod]
        public void SmsEmailSmsStrippedStringGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? ruleId = null;
            //var response = instance.SmsEmailSmsStrippedStringGet(ruleId);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test SmsEmailSmsStrippedStringPost
        /// </summary>
        [TestMethod]
        public void SmsEmailSmsStrippedStringPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //StrippedString body = null;
            //var response = instance.SmsEmailSmsStrippedStringPost(body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test SmsEmailSmsStrippedStringPut
        /// </summary>
        [TestMethod]
        public void SmsEmailSmsStrippedStringPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //StrippedString body = null;
            //int? ruleId = null;
            //var response = instance.SmsEmailSmsStrippedStringPut(body, ruleId);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test SmsEmailSmsStrippedStringsGet
        /// </summary>
        [TestMethod]
        public void SmsEmailSmsStrippedStringsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? limit = null;
            //var response = instance.SmsEmailSmsStrippedStringsGet(page, limit);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
    }

}
