/* 
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.ClickSend.Api;
using IO.Swagger.ClickSend.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InboundSMSRulesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class InboundSMSRulesApiTests
    {
        private InboundSMSRulesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new InboundSMSRulesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InboundSMSRulesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' InboundSMSRulesApi
            //Assert.IsInstanceOfType(typeof(InboundSMSRulesApi), instance, "instance is a InboundSMSRulesApi");
        }

        
        /// <summary>
        /// Test SmsInboundAutomationDelete
        /// </summary>
        [Test]
        public void SmsInboundAutomationDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? inboundRuleId = null;
            //var response = instance.SmsInboundAutomationDelete(inboundRuleId);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test SmsInboundAutomationGet
        /// </summary>
        [Test]
        public void SmsInboundAutomationGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? inboundRuleId = null;
            //var response = instance.SmsInboundAutomationGet(inboundRuleId);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test SmsInboundAutomationPost
        /// </summary>
        [Test]
        public void SmsInboundAutomationPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InboundSMSRule inboundSmsRule = null;
            //var response = instance.SmsInboundAutomationPost(inboundSmsRule);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test SmsInboundAutomationPut
        /// </summary>
        [Test]
        public void SmsInboundAutomationPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? inboundRuleId = null;
            //InboundSMSRule inboundSmsRule = null;
            //var response = instance.SmsInboundAutomationPut(inboundRuleId, inboundSmsRule);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test SmsInboundAutomationsGet
        /// </summary>
        [Test]
        public void SmsInboundAutomationsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? limit = null;
            //var response = instance.SmsInboundAutomationsGet(page, limit);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
