/* 
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.ClickSend.Client;
using IO.ClickSend.ClickSend.Api;
using IO.ClickSend.ClickSend.Model;

namespace IO.ClickSend.Test
{
    /// <summary>
    ///  Class for testing VoiceDeliveryReceiptRulesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by ClickSend Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class VoiceDeliveryReceiptRulesApiTests
    {
        private VoiceDeliveryReceiptRulesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new VoiceDeliveryReceiptRulesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VoiceDeliveryReceiptRulesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' VoiceDeliveryReceiptRulesApi
            //Assert.IsInstanceOfType(typeof(VoiceDeliveryReceiptRulesApi), instance, "instance is a VoiceDeliveryReceiptRulesApi");
        }

        
        /// <summary>
        /// Test VoiceDeliveryReceiptAutomationDelete
        /// </summary>
        [Test]
        public void VoiceDeliveryReceiptAutomationDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? receiptRuleId = null;
            //var response = instance.VoiceDeliveryReceiptAutomationDelete(receiptRuleId);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test VoiceDeliveryReceiptAutomationGet
        /// </summary>
        [Test]
        public void VoiceDeliveryReceiptAutomationGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? receiptRuleId = null;
            //var response = instance.VoiceDeliveryReceiptAutomationGet(receiptRuleId);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test VoiceDeliveryReceiptAutomationPost
        /// </summary>
        [Test]
        public void VoiceDeliveryReceiptAutomationPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DeliveryReceiptRule deliveryReceiptRule = null;
            //var response = instance.VoiceDeliveryReceiptAutomationPost(deliveryReceiptRule);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test VoiceDeliveryReceiptAutomationPut
        /// </summary>
        [Test]
        public void VoiceDeliveryReceiptAutomationPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? receiptRuleId = null;
            //DeliveryReceiptRule deliveryReceiptRule = null;
            //var response = instance.VoiceDeliveryReceiptAutomationPut(receiptRuleId, deliveryReceiptRule);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test VoiceDeliveryReceiptAutomationsGet
        /// </summary>
        [Test]
        public void VoiceDeliveryReceiptAutomationsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string q = null;
            //int? page = null;
            //int? limit = null;
            //var response = instance.VoiceDeliveryReceiptAutomationsGet(q, page, limit);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
