/* 
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.ClickSend.Client;
using IO.ClickSend.ClickSend.Model;

namespace IO.ClickSend.ClickSend.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISMSDeliveryReceiptRulesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete sms delivery receipt automation
        /// </summary>
        /// <remarks>
        /// Delete sms delivery receipt automation
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>string</returns>
        string SmsDeliveryReceiptAutomationDelete (int? receiptRuleId);

        /// <summary>
        /// Delete sms delivery receipt automation
        /// </summary>
        /// <remarks>
        /// Delete sms delivery receipt automation
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> SmsDeliveryReceiptAutomationDeleteWithHttpInfo (int? receiptRuleId);
        /// <summary>
        /// Get specific sms delivery receipt automation
        /// </summary>
        /// <remarks>
        /// Get specific sms delivery receipt automation
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>string</returns>
        string SmsDeliveryReceiptAutomationGet (int? receiptRuleId);

        /// <summary>
        /// Get specific sms delivery receipt automation
        /// </summary>
        /// <remarks>
        /// Get specific sms delivery receipt automation
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> SmsDeliveryReceiptAutomationGetWithHttpInfo (int? receiptRuleId);
        /// <summary>
        /// Create sms delivery receipt automations
        /// </summary>
        /// <remarks>
        /// Create sms delivery receipt automations
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deliveryReceiptRule">sms delivery receipt rule model</param>
        /// <returns>string</returns>
        string SmsDeliveryReceiptAutomationPost (DeliveryReceiptRule deliveryReceiptRule);

        /// <summary>
        /// Create sms delivery receipt automations
        /// </summary>
        /// <remarks>
        /// Create sms delivery receipt automations
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deliveryReceiptRule">sms delivery receipt rule model</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> SmsDeliveryReceiptAutomationPostWithHttpInfo (DeliveryReceiptRule deliveryReceiptRule);
        /// <summary>
        /// Update sms delivery receipt automation
        /// </summary>
        /// <remarks>
        /// Update sms delivery receipt automation
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <param name="deliveryReceiptRule">Delivery receipt rule model</param>
        /// <returns>string</returns>
        string SmsDeliveryReceiptAutomationPut (int? receiptRuleId, DeliveryReceiptRule deliveryReceiptRule);

        /// <summary>
        /// Update sms delivery receipt automation
        /// </summary>
        /// <remarks>
        /// Update sms delivery receipt automation
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <param name="deliveryReceiptRule">Delivery receipt rule model</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> SmsDeliveryReceiptAutomationPutWithHttpInfo (int? receiptRuleId, DeliveryReceiptRule deliveryReceiptRule);
        /// <summary>
        /// Get all sms delivery receipt automations
        /// </summary>
        /// <remarks>
        /// Get all sms delivery receipt automations
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Your keyword or query. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="limit">Number of records per page (optional, default to 10)</param>
        /// <returns>string</returns>
        string SmsDeliveryReceiptAutomationsGet (string q = null, int? page = null, int? limit = null);

        /// <summary>
        /// Get all sms delivery receipt automations
        /// </summary>
        /// <remarks>
        /// Get all sms delivery receipt automations
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Your keyword or query. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="limit">Number of records per page (optional, default to 10)</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> SmsDeliveryReceiptAutomationsGetWithHttpInfo (string q = null, int? page = null, int? limit = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Delete sms delivery receipt automation
        /// </summary>
        /// <remarks>
        /// Delete sms delivery receipt automation
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> SmsDeliveryReceiptAutomationDeleteAsync (int? receiptRuleId);

        /// <summary>
        /// Delete sms delivery receipt automation
        /// </summary>
        /// <remarks>
        /// Delete sms delivery receipt automation
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> SmsDeliveryReceiptAutomationDeleteAsyncWithHttpInfo (int? receiptRuleId);
        /// <summary>
        /// Get specific sms delivery receipt automation
        /// </summary>
        /// <remarks>
        /// Get specific sms delivery receipt automation
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> SmsDeliveryReceiptAutomationGetAsync (int? receiptRuleId);

        /// <summary>
        /// Get specific sms delivery receipt automation
        /// </summary>
        /// <remarks>
        /// Get specific sms delivery receipt automation
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> SmsDeliveryReceiptAutomationGetAsyncWithHttpInfo (int? receiptRuleId);
        /// <summary>
        /// Create sms delivery receipt automations
        /// </summary>
        /// <remarks>
        /// Create sms delivery receipt automations
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deliveryReceiptRule">sms delivery receipt rule model</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> SmsDeliveryReceiptAutomationPostAsync (DeliveryReceiptRule deliveryReceiptRule);

        /// <summary>
        /// Create sms delivery receipt automations
        /// </summary>
        /// <remarks>
        /// Create sms delivery receipt automations
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deliveryReceiptRule">sms delivery receipt rule model</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> SmsDeliveryReceiptAutomationPostAsyncWithHttpInfo (DeliveryReceiptRule deliveryReceiptRule);
        /// <summary>
        /// Update sms delivery receipt automation
        /// </summary>
        /// <remarks>
        /// Update sms delivery receipt automation
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <param name="deliveryReceiptRule">Delivery receipt rule model</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> SmsDeliveryReceiptAutomationPutAsync (int? receiptRuleId, DeliveryReceiptRule deliveryReceiptRule);

        /// <summary>
        /// Update sms delivery receipt automation
        /// </summary>
        /// <remarks>
        /// Update sms delivery receipt automation
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <param name="deliveryReceiptRule">Delivery receipt rule model</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> SmsDeliveryReceiptAutomationPutAsyncWithHttpInfo (int? receiptRuleId, DeliveryReceiptRule deliveryReceiptRule);
        /// <summary>
        /// Get all sms delivery receipt automations
        /// </summary>
        /// <remarks>
        /// Get all sms delivery receipt automations
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Your keyword or query. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="limit">Number of records per page (optional, default to 10)</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> SmsDeliveryReceiptAutomationsGetAsync (string q = null, int? page = null, int? limit = null);

        /// <summary>
        /// Get all sms delivery receipt automations
        /// </summary>
        /// <remarks>
        /// Get all sms delivery receipt automations
        /// </remarks>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Your keyword or query. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="limit">Number of records per page (optional, default to 10)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> SmsDeliveryReceiptAutomationsGetAsyncWithHttpInfo (string q = null, int? page = null, int? limit = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SMSDeliveryReceiptRulesApi : ISMSDeliveryReceiptRulesApi
    {
        private IO.ClickSend.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SMSDeliveryReceiptRulesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SMSDeliveryReceiptRulesApi(String basePath)
        {
            this.Configuration = new IO.ClickSend.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.ClickSend.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SMSDeliveryReceiptRulesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SMSDeliveryReceiptRulesApi(IO.ClickSend.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.ClickSend.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.ClickSend.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.ClickSend.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.ClickSend.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Delete sms delivery receipt automation Delete sms delivery receipt automation
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>string</returns>
        public string SmsDeliveryReceiptAutomationDelete (int? receiptRuleId)
        {
             ApiResponse<string> localVarResponse = SmsDeliveryReceiptAutomationDeleteWithHttpInfo(receiptRuleId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete sms delivery receipt automation Delete sms delivery receipt automation
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > SmsDeliveryReceiptAutomationDeleteWithHttpInfo (int? receiptRuleId)
        {
            // verify the required parameter 'receiptRuleId' is set
            if (receiptRuleId == null)
                throw new ApiException(400, "Missing required parameter 'receiptRuleId' when calling SMSDeliveryReceiptRulesApi->SmsDeliveryReceiptAutomationDelete");

            var localVarPath = "/automations/sms/receipts/{receipt_rule_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (receiptRuleId != null) localVarPathParams.Add("receipt_rule_id", this.Configuration.ApiClient.ParameterToString(receiptRuleId)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsDeliveryReceiptAutomationDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Delete sms delivery receipt automation Delete sms delivery receipt automation
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> SmsDeliveryReceiptAutomationDeleteAsync (int? receiptRuleId)
        {
             ApiResponse<string> localVarResponse = await SmsDeliveryReceiptAutomationDeleteAsyncWithHttpInfo(receiptRuleId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete sms delivery receipt automation Delete sms delivery receipt automation
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> SmsDeliveryReceiptAutomationDeleteAsyncWithHttpInfo (int? receiptRuleId)
        {
            // verify the required parameter 'receiptRuleId' is set
            if (receiptRuleId == null)
                throw new ApiException(400, "Missing required parameter 'receiptRuleId' when calling SMSDeliveryReceiptRulesApi->SmsDeliveryReceiptAutomationDelete");

            var localVarPath = "/automations/sms/receipts/{receipt_rule_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (receiptRuleId != null) localVarPathParams.Add("receipt_rule_id", this.Configuration.ApiClient.ParameterToString(receiptRuleId)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsDeliveryReceiptAutomationDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get specific sms delivery receipt automation Get specific sms delivery receipt automation
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>string</returns>
        public string SmsDeliveryReceiptAutomationGet (int? receiptRuleId)
        {
             ApiResponse<string> localVarResponse = SmsDeliveryReceiptAutomationGetWithHttpInfo(receiptRuleId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get specific sms delivery receipt automation Get specific sms delivery receipt automation
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > SmsDeliveryReceiptAutomationGetWithHttpInfo (int? receiptRuleId)
        {
            // verify the required parameter 'receiptRuleId' is set
            if (receiptRuleId == null)
                throw new ApiException(400, "Missing required parameter 'receiptRuleId' when calling SMSDeliveryReceiptRulesApi->SmsDeliveryReceiptAutomationGet");

            var localVarPath = "/automations/sms/receipts/{receipt_rule_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (receiptRuleId != null) localVarPathParams.Add("receipt_rule_id", this.Configuration.ApiClient.ParameterToString(receiptRuleId)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsDeliveryReceiptAutomationGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get specific sms delivery receipt automation Get specific sms delivery receipt automation
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> SmsDeliveryReceiptAutomationGetAsync (int? receiptRuleId)
        {
             ApiResponse<string> localVarResponse = await SmsDeliveryReceiptAutomationGetAsyncWithHttpInfo(receiptRuleId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get specific sms delivery receipt automation Get specific sms delivery receipt automation
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> SmsDeliveryReceiptAutomationGetAsyncWithHttpInfo (int? receiptRuleId)
        {
            // verify the required parameter 'receiptRuleId' is set
            if (receiptRuleId == null)
                throw new ApiException(400, "Missing required parameter 'receiptRuleId' when calling SMSDeliveryReceiptRulesApi->SmsDeliveryReceiptAutomationGet");

            var localVarPath = "/automations/sms/receipts/{receipt_rule_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (receiptRuleId != null) localVarPathParams.Add("receipt_rule_id", this.Configuration.ApiClient.ParameterToString(receiptRuleId)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsDeliveryReceiptAutomationGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Create sms delivery receipt automations Create sms delivery receipt automations
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deliveryReceiptRule">sms delivery receipt rule model</param>
        /// <returns>string</returns>
        public string SmsDeliveryReceiptAutomationPost (DeliveryReceiptRule deliveryReceiptRule)
        {
             ApiResponse<string> localVarResponse = SmsDeliveryReceiptAutomationPostWithHttpInfo(deliveryReceiptRule);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create sms delivery receipt automations Create sms delivery receipt automations
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deliveryReceiptRule">sms delivery receipt rule model</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > SmsDeliveryReceiptAutomationPostWithHttpInfo (DeliveryReceiptRule deliveryReceiptRule)
        {
            // verify the required parameter 'deliveryReceiptRule' is set
            if (deliveryReceiptRule == null)
                throw new ApiException(400, "Missing required parameter 'deliveryReceiptRule' when calling SMSDeliveryReceiptRulesApi->SmsDeliveryReceiptAutomationPost");

            var localVarPath = "/automations/sms/receipts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (deliveryReceiptRule != null && deliveryReceiptRule.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(deliveryReceiptRule); // http body (model) parameter
            }
            else
            {
                localVarPostBody = deliveryReceiptRule; // byte array
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsDeliveryReceiptAutomationPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Create sms delivery receipt automations Create sms delivery receipt automations
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deliveryReceiptRule">sms delivery receipt rule model</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> SmsDeliveryReceiptAutomationPostAsync (DeliveryReceiptRule deliveryReceiptRule)
        {
             ApiResponse<string> localVarResponse = await SmsDeliveryReceiptAutomationPostAsyncWithHttpInfo(deliveryReceiptRule);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create sms delivery receipt automations Create sms delivery receipt automations
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deliveryReceiptRule">sms delivery receipt rule model</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> SmsDeliveryReceiptAutomationPostAsyncWithHttpInfo (DeliveryReceiptRule deliveryReceiptRule)
        {
            // verify the required parameter 'deliveryReceiptRule' is set
            if (deliveryReceiptRule == null)
                throw new ApiException(400, "Missing required parameter 'deliveryReceiptRule' when calling SMSDeliveryReceiptRulesApi->SmsDeliveryReceiptAutomationPost");

            var localVarPath = "/automations/sms/receipts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (deliveryReceiptRule != null && deliveryReceiptRule.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(deliveryReceiptRule); // http body (model) parameter
            }
            else
            {
                localVarPostBody = deliveryReceiptRule; // byte array
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsDeliveryReceiptAutomationPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Update sms delivery receipt automation Update sms delivery receipt automation
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <param name="deliveryReceiptRule">Delivery receipt rule model</param>
        /// <returns>string</returns>
        public string SmsDeliveryReceiptAutomationPut (int? receiptRuleId, DeliveryReceiptRule deliveryReceiptRule)
        {
             ApiResponse<string> localVarResponse = SmsDeliveryReceiptAutomationPutWithHttpInfo(receiptRuleId, deliveryReceiptRule);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update sms delivery receipt automation Update sms delivery receipt automation
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <param name="deliveryReceiptRule">Delivery receipt rule model</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > SmsDeliveryReceiptAutomationPutWithHttpInfo (int? receiptRuleId, DeliveryReceiptRule deliveryReceiptRule)
        {
            // verify the required parameter 'receiptRuleId' is set
            if (receiptRuleId == null)
                throw new ApiException(400, "Missing required parameter 'receiptRuleId' when calling SMSDeliveryReceiptRulesApi->SmsDeliveryReceiptAutomationPut");
            // verify the required parameter 'deliveryReceiptRule' is set
            if (deliveryReceiptRule == null)
                throw new ApiException(400, "Missing required parameter 'deliveryReceiptRule' when calling SMSDeliveryReceiptRulesApi->SmsDeliveryReceiptAutomationPut");

            var localVarPath = "/automations/sms/receipts/{receipt_rule_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (receiptRuleId != null) localVarPathParams.Add("receipt_rule_id", this.Configuration.ApiClient.ParameterToString(receiptRuleId)); // path parameter
            if (deliveryReceiptRule != null && deliveryReceiptRule.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(deliveryReceiptRule); // http body (model) parameter
            }
            else
            {
                localVarPostBody = deliveryReceiptRule; // byte array
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsDeliveryReceiptAutomationPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Update sms delivery receipt automation Update sms delivery receipt automation
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <param name="deliveryReceiptRule">Delivery receipt rule model</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> SmsDeliveryReceiptAutomationPutAsync (int? receiptRuleId, DeliveryReceiptRule deliveryReceiptRule)
        {
             ApiResponse<string> localVarResponse = await SmsDeliveryReceiptAutomationPutAsyncWithHttpInfo(receiptRuleId, deliveryReceiptRule);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update sms delivery receipt automation Update sms delivery receipt automation
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="receiptRuleId">Receipt rule id</param>
        /// <param name="deliveryReceiptRule">Delivery receipt rule model</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> SmsDeliveryReceiptAutomationPutAsyncWithHttpInfo (int? receiptRuleId, DeliveryReceiptRule deliveryReceiptRule)
        {
            // verify the required parameter 'receiptRuleId' is set
            if (receiptRuleId == null)
                throw new ApiException(400, "Missing required parameter 'receiptRuleId' when calling SMSDeliveryReceiptRulesApi->SmsDeliveryReceiptAutomationPut");
            // verify the required parameter 'deliveryReceiptRule' is set
            if (deliveryReceiptRule == null)
                throw new ApiException(400, "Missing required parameter 'deliveryReceiptRule' when calling SMSDeliveryReceiptRulesApi->SmsDeliveryReceiptAutomationPut");

            var localVarPath = "/automations/sms/receipts/{receipt_rule_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (receiptRuleId != null) localVarPathParams.Add("receipt_rule_id", this.Configuration.ApiClient.ParameterToString(receiptRuleId)); // path parameter
            if (deliveryReceiptRule != null && deliveryReceiptRule.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(deliveryReceiptRule); // http body (model) parameter
            }
            else
            {
                localVarPostBody = deliveryReceiptRule; // byte array
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsDeliveryReceiptAutomationPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get all sms delivery receipt automations Get all sms delivery receipt automations
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Your keyword or query. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="limit">Number of records per page (optional, default to 10)</param>
        /// <returns>string</returns>
        public string SmsDeliveryReceiptAutomationsGet (string q = null, int? page = null, int? limit = null)
        {
             ApiResponse<string> localVarResponse = SmsDeliveryReceiptAutomationsGetWithHttpInfo(q, page, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get all sms delivery receipt automations Get all sms delivery receipt automations
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Your keyword or query. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="limit">Number of records per page (optional, default to 10)</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > SmsDeliveryReceiptAutomationsGetWithHttpInfo (string q = null, int? page = null, int? limit = null)
        {

            var localVarPath = "/automations/sms/receipts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (q != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "q", q)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsDeliveryReceiptAutomationsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get all sms delivery receipt automations Get all sms delivery receipt automations
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Your keyword or query. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="limit">Number of records per page (optional, default to 10)</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> SmsDeliveryReceiptAutomationsGetAsync (string q = null, int? page = null, int? limit = null)
        {
             ApiResponse<string> localVarResponse = await SmsDeliveryReceiptAutomationsGetAsyncWithHttpInfo(q, page, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get all sms delivery receipt automations Get all sms delivery receipt automations
        /// </summary>
        /// <exception cref="IO.ClickSend.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="q">Your keyword or query. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="limit">Number of records per page (optional, default to 10)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> SmsDeliveryReceiptAutomationsGetAsyncWithHttpInfo (string q = null, int? page = null, int? limit = null)
        {

            var localVarPath = "/automations/sms/receipts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (q != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "q", q)); // query parameter
            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsDeliveryReceiptAutomationsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

    }
}
