/* 
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using ClickSendDateConverter = IO.ClickSend.Client.ClickSendDateConverter;

namespace IO.ClickSend.ClickSend.Model
{
    /// <summary>
    /// Model for Inbound SMS Rules
    /// </summary>
    [DataContract]
    [JsonConverter(typeof(JsonSubtypes), "classType")]
    public partial class InboundSMSRule :  IEquatable<InboundSMSRule>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InboundSMSRule" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InboundSMSRule() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InboundSMSRule" /> class.
        /// </summary>
        /// <param name="dedicatedNumber">Dedicated Number. Can be &#39;*&#39; to apply to all numbers. (required).</param>
        /// <param name="ruleName">Rule Name. (required).</param>
        /// <param name="messageSearchType">Message Search Type: 0&#x3D;Any message, 1&#x3D;starts with, 2&#x3D;contains, 3&#x3D;does not contain. (required).</param>
        /// <param name="messageSearchTerm">Message search term. (required).</param>
        /// <param name="action">Action to be taken (AUTO_REPLY, EMAIL_USER, EMAIL_FIXED, URL, SMS, POLL, GROUP_SMS, MOVE_CONTACT, CREATE_CONTACT, CREATE_CONTACT_PLUS_EMAIL, CREATE_CONTACT_PLUS_NAME_EMAIL CREATE_CONTACT_PLUS_NAME, SMPP, NONE). (required).</param>
        /// <param name="actionAddress">Action address. (required).</param>
        /// <param name="enabled">Enabled: Disabled&#x3D;0 or Enabled&#x3D;1. (required).</param>
        /// <param name="webhookType">post, get, or json. post by default.</param>
        public InboundSMSRule(string dedicatedNumber = default(string), string ruleName = default(string), decimal? messageSearchType = default(decimal?), string messageSearchTerm = default(string), string action = default(string), string actionAddress = default(string), decimal? enabled = default(decimal?), string webhookType = default(string))
        {
            // to ensure "dedicatedNumber" is required (not null)
            if (dedicatedNumber == null)
            {
                throw new InvalidDataException("dedicatedNumber is a required property for InboundSMSRule and cannot be null");
            }
            else
            {
                this.DedicatedNumber = dedicatedNumber;
            }
            // to ensure "ruleName" is required (not null)
            if (ruleName == null)
            {
                throw new InvalidDataException("ruleName is a required property for InboundSMSRule and cannot be null");
            }
            else
            {
                this.RuleName = ruleName;
            }
            // to ensure "messageSearchType" is required (not null)
            if (messageSearchType == null)
            {
                throw new InvalidDataException("messageSearchType is a required property for InboundSMSRule and cannot be null");
            }
            else
            {
                this.MessageSearchType = messageSearchType;
            }
            // to ensure "messageSearchTerm" is required (not null)
            if (messageSearchTerm == null)
            {
                throw new InvalidDataException("messageSearchTerm is a required property for InboundSMSRule and cannot be null");
            }
            else
            {
                this.MessageSearchTerm = messageSearchTerm;
            }
            // to ensure "action" is required (not null)
            if (action == null)
            {
                throw new InvalidDataException("action is a required property for InboundSMSRule and cannot be null");
            }
            else
            {
                this.Action = action;
            }
            // to ensure "actionAddress" is required (not null)
            if (actionAddress == null)
            {
                throw new InvalidDataException("actionAddress is a required property for InboundSMSRule and cannot be null");
            }
            else
            {
                this.ActionAddress = actionAddress;
            }
            // to ensure "enabled" is required (not null)
            if (enabled == null)
            {
                throw new InvalidDataException("enabled is a required property for InboundSMSRule and cannot be null");
            }
            else
            {
                this.Enabled = enabled;
            }
            this.WebhookType = webhookType;
        }
        
        /// <summary>
        /// Dedicated Number. Can be &#39;*&#39; to apply to all numbers.
        /// </summary>
        /// <value>Dedicated Number. Can be &#39;*&#39; to apply to all numbers.</value>
        [DataMember(Name="dedicated_number", EmitDefaultValue=false)]
        public string DedicatedNumber { get; set; }

        /// <summary>
        /// Rule Name.
        /// </summary>
        /// <value>Rule Name.</value>
        [DataMember(Name="rule_name", EmitDefaultValue=false)]
        public string RuleName { get; set; }

        /// <summary>
        /// Message Search Type: 0&#x3D;Any message, 1&#x3D;starts with, 2&#x3D;contains, 3&#x3D;does not contain.
        /// </summary>
        /// <value>Message Search Type: 0&#x3D;Any message, 1&#x3D;starts with, 2&#x3D;contains, 3&#x3D;does not contain.</value>
        [DataMember(Name="message_search_type", EmitDefaultValue=false)]
        public decimal? MessageSearchType { get; set; }

        /// <summary>
        /// Message search term.
        /// </summary>
        /// <value>Message search term.</value>
        [DataMember(Name="message_search_term", EmitDefaultValue=false)]
        public string MessageSearchTerm { get; set; }

        /// <summary>
        /// Action to be taken (AUTO_REPLY, EMAIL_USER, EMAIL_FIXED, URL, SMS, POLL, GROUP_SMS, MOVE_CONTACT, CREATE_CONTACT, CREATE_CONTACT_PLUS_EMAIL, CREATE_CONTACT_PLUS_NAME_EMAIL CREATE_CONTACT_PLUS_NAME, SMPP, NONE).
        /// </summary>
        /// <value>Action to be taken (AUTO_REPLY, EMAIL_USER, EMAIL_FIXED, URL, SMS, POLL, GROUP_SMS, MOVE_CONTACT, CREATE_CONTACT, CREATE_CONTACT_PLUS_EMAIL, CREATE_CONTACT_PLUS_NAME_EMAIL CREATE_CONTACT_PLUS_NAME, SMPP, NONE).</value>
        [DataMember(Name="action", EmitDefaultValue=false)]
        public string Action { get; set; }

        /// <summary>
        /// Action address.
        /// </summary>
        /// <value>Action address.</value>
        [DataMember(Name="action_address", EmitDefaultValue=false)]
        public string ActionAddress { get; set; }

        /// <summary>
        /// Enabled: Disabled&#x3D;0 or Enabled&#x3D;1.
        /// </summary>
        /// <value>Enabled: Disabled&#x3D;0 or Enabled&#x3D;1.</value>
        [DataMember(Name="enabled", EmitDefaultValue=false)]
        public decimal? Enabled { get; set; }

        /// <summary>
        /// post, get, or json. post by default
        /// </summary>
        /// <value>post, get, or json. post by default</value>
        [DataMember(Name="webhook_type", EmitDefaultValue=false)]
        public string WebhookType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InboundSMSRule {\n");
            sb.Append("  DedicatedNumber: ").Append(DedicatedNumber).Append("\n");
            sb.Append("  RuleName: ").Append(RuleName).Append("\n");
            sb.Append("  MessageSearchType: ").Append(MessageSearchType).Append("\n");
            sb.Append("  MessageSearchTerm: ").Append(MessageSearchTerm).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  ActionAddress: ").Append(ActionAddress).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  WebhookType: ").Append(WebhookType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InboundSMSRule);
        }

        /// <summary>
        /// Returns true if InboundSMSRule instances are equal
        /// </summary>
        /// <param name="input">Instance of InboundSMSRule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InboundSMSRule input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DedicatedNumber == input.DedicatedNumber ||
                    (this.DedicatedNumber != null &&
                    this.DedicatedNumber.Equals(input.DedicatedNumber))
                ) && 
                (
                    this.RuleName == input.RuleName ||
                    (this.RuleName != null &&
                    this.RuleName.Equals(input.RuleName))
                ) && 
                (
                    this.MessageSearchType == input.MessageSearchType ||
                    (this.MessageSearchType != null &&
                    this.MessageSearchType.Equals(input.MessageSearchType))
                ) && 
                (
                    this.MessageSearchTerm == input.MessageSearchTerm ||
                    (this.MessageSearchTerm != null &&
                    this.MessageSearchTerm.Equals(input.MessageSearchTerm))
                ) && 
                (
                    this.Action == input.Action ||
                    (this.Action != null &&
                    this.Action.Equals(input.Action))
                ) && 
                (
                    this.ActionAddress == input.ActionAddress ||
                    (this.ActionAddress != null &&
                    this.ActionAddress.Equals(input.ActionAddress))
                ) && 
                (
                    this.Enabled == input.Enabled ||
                    (this.Enabled != null &&
                    this.Enabled.Equals(input.Enabled))
                ) && 
                (
                    this.WebhookType == input.WebhookType ||
                    (this.WebhookType != null &&
                    this.WebhookType.Equals(input.WebhookType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DedicatedNumber != null)
                    hashCode = hashCode * 59 + this.DedicatedNumber.GetHashCode();
                if (this.RuleName != null)
                    hashCode = hashCode * 59 + this.RuleName.GetHashCode();
                if (this.MessageSearchType != null)
                    hashCode = hashCode * 59 + this.MessageSearchType.GetHashCode();
                if (this.MessageSearchTerm != null)
                    hashCode = hashCode * 59 + this.MessageSearchTerm.GetHashCode();
                if (this.Action != null)
                    hashCode = hashCode * 59 + this.Action.GetHashCode();
                if (this.ActionAddress != null)
                    hashCode = hashCode * 59 + this.ActionAddress.GetHashCode();
                if (this.Enabled != null)
                    hashCode = hashCode * 59 + this.Enabled.GetHashCode();
                if (this.WebhookType != null)
                    hashCode = hashCode * 59 + this.WebhookType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
