/* 
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.ClickSend.ClickSend.Api;
using IO.ClickSend.ClickSend.Model;
using IO.ClickSend.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.ClickSend.Test
{
    /// <summary>
    ///  Class for testing AccountVerify
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by ClickSend Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountVerifyTests
    {
        // TODO uncomment below to declare an instance variable for AccountVerify
        //private AccountVerify instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountVerify
            //instance = new AccountVerify();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountVerify
        /// </summary>
        [Test]
        public void AccountVerifyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountVerify
            //Assert.IsInstanceOfType<AccountVerify> (instance, "variable 'instance' is a AccountVerify");
        }


        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'UserPhone'
        /// </summary>
        [Test]
        public void UserPhoneTest()
        {
            // TODO unit test for the property 'UserPhone'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
