/* 
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.ClickSend.ClickSend.Api;
using IO.ClickSend.ClickSend.Model;
using IO.ClickSend.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.ClickSend.Test
{
    /// <summary>
    ///  Class for testing ContactList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by ClickSend Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContactListTests
    {
        // TODO uncomment below to declare an instance variable for ContactList
        //private ContactList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContactList
            //instance = new ContactList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContactList
        /// </summary>
        [Test]
        public void ContactListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ContactList
            //Assert.IsInstanceOfType<ContactList> (instance, "variable 'instance' is a ContactList");
        }


        /// <summary>
        /// Test the property 'ListName'
        /// </summary>
        [Test]
        public void ListNameTest()
        {
            // TODO unit test for the property 'ListName'
        }

    }

}
