/* 
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.ClickSend.ClickSend.Api;
using IO.ClickSend.ClickSend.Model;
using IO.ClickSend.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.ClickSend.Test
{
    /// <summary>
    ///  Class for testing EmailFrom
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by ClickSend Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmailFromTests
    {
        // TODO uncomment below to declare an instance variable for EmailFrom
        //private EmailFrom instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EmailFrom
            //instance = new EmailFrom();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmailFrom
        /// </summary>
        [Test]
        public void EmailFromInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EmailFrom
            //Assert.IsInstanceOfType<EmailFrom> (instance, "variable 'instance' is a EmailFrom");
        }


        /// <summary>
        /// Test the property 'EmailAddressId'
        /// </summary>
        [Test]
        public void EmailAddressIdTest()
        {
            // TODO unit test for the property 'EmailAddressId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
