/* 
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.ClickSend.ClickSend.Api;
using IO.ClickSend.ClickSend.Model;
using IO.ClickSend.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.ClickSend.Test
{
    /// <summary>
    ///  Class for testing EmailSMSAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by ClickSend Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmailSMSAddressTests
    {
        // TODO uncomment below to declare an instance variable for EmailSMSAddress
        //private EmailSMSAddress instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EmailSMSAddress
            //instance = new EmailSMSAddress();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmailSMSAddress
        /// </summary>
        [Test]
        public void EmailSMSAddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EmailSMSAddress
            //Assert.IsInstanceOfType<EmailSMSAddress> (instance, "variable 'instance' is a EmailSMSAddress");
        }


        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Test]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'SubaccountId'
        /// </summary>
        [Test]
        public void SubaccountIdTest()
        {
            // TODO unit test for the property 'SubaccountId'
        }

    }

}
