/* 
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.ClickSend.ClickSend.Api;
using IO.ClickSend.ClickSend.Model;
using IO.ClickSend.Client;
using System.Reflection;
using Newtonsoft.Json;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace IO.ClickSend.Test
{
    /// <summary>
    ///  Class for testing ForgotUsername
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by ClickSend Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class ForgotUsernameTests
    {
        // TODO uncomment below to declare an instance variable for ForgotUsername
        //private ForgotUsername instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of ForgotUsername
            //instance = new ForgotUsername();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ForgotUsername
        /// </summary>
        [TestMethod]
        public void ForgotUsernameInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ForgotUsername
            //Assert.IsInstanceOfType<ForgotUsername> (instance, "variable 'instance' is a ForgotUsername");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [TestMethod]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [TestMethod]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

    }

}
