/* 
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.ClickSend.ClickSend.Api;
using IO.ClickSend.ClickSend.Model;
using IO.ClickSend.Client;
using System.Reflection;
using Newtonsoft.Json;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace IO.ClickSend.Test
{
    /// <summary>
    ///  Class for testing MmsCampaign
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by ClickSend Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class MmsCampaignTests
    {
        // TODO uncomment below to declare an instance variable for MmsCampaign
        //private MmsCampaign instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of MmsCampaign
            //instance = new MmsCampaign();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MmsCampaign
        /// </summary>
        [TestMethod]
        public void MmsCampaignInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MmsCampaign
            //Assert.IsInstanceOfType<MmsCampaign> (instance, "variable 'instance' is a MmsCampaign");
        }


        /// <summary>
        /// Test the property 'ListId'
        /// </summary>
        [TestMethod]
        public void ListIdTest()
        {
            // TODO unit test for the property 'ListId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [TestMethod]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [TestMethod]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [TestMethod]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [TestMethod]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [TestMethod]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'MediaFile'
        /// </summary>
        [TestMethod]
        public void MediaFileTest()
        {
            // TODO unit test for the property 'MediaFile'
        }

    }

}
