/* 
 * ClickSend v3 API
 *
 *  This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 
 *
 * OpenAPI spec version: 3.1
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.ClickSend.Api;
using IO.Swagger.ClickSend.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SmsTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SmsTemplateTests
    {
        // TODO uncomment below to declare an instance variable for SmsTemplate
        //private SmsTemplate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SmsTemplate
            //instance = new SmsTemplate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SmsTemplate
        /// </summary>
        [Test]
        public void SmsTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SmsTemplate
            //Assert.IsInstanceOfType<SmsTemplate> (instance, "variable 'instance' is a SmsTemplate");
        }


        /// <summary>
        /// Test the property 'TemplateName'
        /// </summary>
        [Test]
        public void TemplateNameTest()
        {
            // TODO unit test for the property 'TemplateName'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

    }

}
