/* 
 * ClickSend v3 REST API
 *
 *  This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 
 *
 * OpenAPI spec version: 3.1.0
 * Contact: support@clicksend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.ClickSend.Client.Api;
using IO.Swagger.ClickSend.Client.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InboundSMSRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InboundSMSRuleTests
    {
        // TODO uncomment below to declare an instance variable for InboundSMSRule
        //private InboundSMSRule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InboundSMSRule
            //instance = new InboundSMSRule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InboundSMSRule
        /// </summary>
        [Test]
        public void InboundSMSRuleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InboundSMSRule
            //Assert.IsInstanceOfType<InboundSMSRule> (instance, "variable 'instance' is a InboundSMSRule");
        }


        /// <summary>
        /// Test the property 'DedicatedNumber'
        /// </summary>
        [Test]
        public void DedicatedNumberTest()
        {
            // TODO unit test for the property 'DedicatedNumber'
        }
        /// <summary>
        /// Test the property 'RuleName'
        /// </summary>
        [Test]
        public void RuleNameTest()
        {
            // TODO unit test for the property 'RuleName'
        }
        /// <summary>
        /// Test the property 'MessageSearchType'
        /// </summary>
        [Test]
        public void MessageSearchTypeTest()
        {
            // TODO unit test for the property 'MessageSearchType'
        }
        /// <summary>
        /// Test the property 'MessageSearchTerm'
        /// </summary>
        [Test]
        public void MessageSearchTermTest()
        {
            // TODO unit test for the property 'MessageSearchTerm'
        }
        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'ActionAddress'
        /// </summary>
        [Test]
        public void ActionAddressTest()
        {
            // TODO unit test for the property 'ActionAddress'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

    }

}
